### ISSUE TITLE
【bug】wrong description in apiserver-builder/docs/concepts/auth.md

### ISSUE THREAD

**Issue by woodliu** [kubernetes-incubator/apiserver-builder#228]
in section Client Certificate Authentication,there are some words:
"By default, a main Kubernetes API server configured with the --client-ca-file option automatically creates a ConfigMap called extension-apiserver-authentication in the kube-system namespac"

but according to https://kubernetes.io/docs/reference/generated/kube-apiserver/, extension-apiserver-authentication shoud be generated by --proxy-client-cert-file，not --client-ca-file

**Comment by DirectXMan12** [comment]
If you look closely in that documentation, you'll notice that it says `requestheader-client-ca-file` is used.  If you look at the code, you'll see that `client-ca-file` is also used.  If at least one of those is present, then the ConfigMap will be created, since the purpose of the configmap is to communicate the CAs used to validate RequestHeader auth and *normal* client cert auth.

**Comment by woodliu** [comment]
@DirectXMan12 i have noticed that, i just want to reject myself.thank you for your reply,the documentations are very good for the beginner!
